name: imdb
channels:
  - conda-forge
dependencies:
  - matplotlib
  - seaborn
  - numpy
  - keyring
  - pandas
  - python-duckdb
  - python-dotenv
  - ploomber
  - pip
  - pip:
    - jupyter-book
    - pkgmt>=0.1.7
    - duckdb==0.8.1
    - duckdb-engine==0.9.1
    - jupysql-plugin==0.1.9
    - jupysql==0.9.0
    - urllib3==1.26.6
    - requests
